version: '3.6'

services:
    postgres:
        image: postgres:12
        ports:
            - 5433:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: phamhieu244
            POSTGRES_DB: messenger
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: phamhieu244
        ports:
            - 8999:80
    redis:
        image: redis
        ports:
            - 6380:6379
    # messenger-server:
    #     container_name: messenger-server
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - 4000:4000
    #     depends_on:
    #         - postgres
    #         - redis
    #         - pgadmin
