POST http://localhost:4000/user/register
Content-Type: application/json

{
    "phone_or_email": "phamhieu2404@gmail.com",
    "password": "Phamhieu244",
    "repassword": "Phamhieu244",
    "fullname": "Phạm Hiếu"
}

###

POST http://localhost:4000/user/login
Content-Type: application/json

{
    "phone_or_email": "phamhieu2404@gmail.com",
    "password": "Phamhieu244"
}

// hieu: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDE4ZDAxMy00MzA2LTQ3YTEtYTgwNS01ZTk2OGRjNTU3N2MiLCJpYXQiOjE2NTQ1MDg2NjN9.lFhMAchUjJwlg7qnTC8Ecp5NTqkLlWXlBM1YfrnxqHQ
// tuan: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs
// vy: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNGY4ZTljMi02NTRiLTQ4NTItYWU4MS0zMWQxNTQyNDc0NDEiLCJpYXQiOjE2NTQ1NzAyOTV9.-76B8q5r8uge3OPkPhK5_ISLzHSVyR-571PbeceFNnk

###

PATCH http://localhost:4000/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

###

PATCH http://localhost:4000/user/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDE4ZDAxMy00MzA2LTQ3YTEtYTgwNS01ZTk2OGRjNTU3N2MiLCJpYXQiOjE2NTQ1MDg2NjN9.lFhMAchUjJwlg7qnTC8Ecp5NTqkLlWXlBM1YfrnxqHQ

{
    "new_avatar": ""
}

###

GET http://localhost:4000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDE4ZDAxMy00MzA2LTQ3YTEtYTgwNS01ZTk2OGRjNTU3N2MiLCJpYXQiOjE2NTQ1MDg2NjN9.lFhMAchUjJwlg7qnTC8Ecp5NTqkLlWXlBM1YfrnxqHQ

###

GET http://localhost:4000/user/search?pattern=h
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDE4ZDAxMy00MzA2LTQ3YTEtYTgwNS01ZTk2OGRjNTU3N2MiLCJpYXQiOjE2NTQ1MDg2NjN9.lFhMAchUjJwlg7qnTC8Ecp5NTqkLlWXlBM1YfrnxqHQ

###

POST http://localhost:4000/chat/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

{
    "guest_id": "24f8e9c2-654b-4852-ae81-31d154247441"
}

###

GET http://localhost:4000/chat/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

###

DELETE http://localhost:4000/chat/delete?chat_id=f648dc39-1184-4e5a-8875-53136662f0e1&guest_chat_id=null&guest_id=24f8e9c2-654b-4852-ae81-31d154247441
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

###

POST http://localhost:4000/message/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

{
    "content": "di choi game ty khong?",
    "type": "text",
    "chat_id": "a5c7b03e-4ec3-4093-931e-50dcbe4702ed",
    "guest_id": "3018d013-4306-47a1-a805-5e968dc5577c",
    "guest_chat_id": "c4da00f8-3681-41e9-abd7-9b74d9964f41"
}

###

GET http://localhost:4000/message/a5c7b03e-4ec3-4093-931e-50dcbe4702ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjJiZGZhZi00OTBjLTQzYTYtYTc4OC1kNWU2MjM5ODBlZDAiLCJpYXQiOjE2NTQ1MTA3NzJ9.5LY_m500pGwxZDKrM94w0-OVUgaaSEvKoozYwV6aOVs

###



