import { BACKGROUND_COLOR, MAIN_COLOR, MAIN_EMOJI } from '../interfaces'

export const MAIN_COLORS: MAIN_COLOR[] = [
  MAIN_COLOR.DANGER,
  MAIN_COLOR.DARK,
  MAIN_COLOR.INFO,
  MAIN_COLOR.PRIMARY,
  MAIN_COLOR.SECONDARY,
  MAIN_COLOR.SUCCESS,
  MAIN_COLOR.VIOLET,
  MAIN_COLOR.WARNING,
]

export const BACKGROUND_COLORS: BACKGROUND_COLOR[] = [
  BACKGROUND_COLOR.white,
  BACKGROUND_COLOR.blue,
  BACKGROUND_COLOR.green,
  BACKGROUND_COLOR.orange,
  BACKGROUND_COLOR.red,
  BACKGROUND_COLOR.violet,
]

export const MAIN_EMOJIS: string[] = [
  MAIN_EMOJI.LIKE,
  MAIN_EMOJI.LOVE,
  MAIN_EMOJI.SMILE,
  MAIN_EMOJI.POO,
  MAIN_EMOJI.BALL,
  MAIN_EMOJI.GHOST,
  MAIN_EMOJI.BAN,
]

export const LIMIT_MESSAGES: number = 20
